### ISSUE TITLE
Add `#[try]` that does Ok-wrapping but doesn't remove `Result` from function signature

### ISSUE THREAD

**Issue by dlight** [Nullus157/culpa#6]
Fehler was a good experiment in Ok-wrapping but I think that removing `Result` and `Option` is a bit too much. This view is also reflected by withoutboats' article in [The registers of Rust](https://without.boats/blog/the-registers-of-rust/), where it is said:

> I've written before about why I think ["Ok" wrapping](https://without.boats/blog/why-ok-wrapping/) functions would be a very good addition to Rust, and even [implemented them as well](https://github.com/withoutboats/fehler). The only way my view has evolved since then (and here I think I am now more in line with the Rust project) is that using a syntax like try fn that doesn’t change the return type, so you can specify Option or Result, is probably the right approach for Rust. But overall having a syntax that keeps the user fully inside the effect (which is what Ok-wrapping really means), rather than halfway, would be not only more convenient but also more consistent with asynchrony and iteration.

I'm not proposing changing the `#[throws]` macro but instead defining a new macro that does not change the return type. And maybe it should be called `#[try]`, with the understanding that `#[try] fn f() -> Result<i32>` could eventually become `try fn f() -> Result<i32>` if Ok-wrapping ever became part of the Rust proper.

**Comment by Nemo157** [comment]
Finally got around to publishing this in 1.0.2
